const Category = require('./category.model');
const Product = require('../products/product.model');
const AppError = require('../../common/errors/AppError');

/**
 * Get all categories sorted by sortOrder
 */
const getAllCategories = async () => {
  return await Category.find({}).sort({ sortOrder: 1, createdAt: -1 });
};

/**
 * Get a category by its ID
 */
const getCategoryById = async (id) => {
  const category = await Category.findById(id);
  if (!category) {
    throw new AppError('Category not found', 404);
  }
  return category;
};

/**
 * Get a category by its slug
 */
const getCategoryBySlug = async (slug) => {
  const category = await Category.findOne({ slug });
  if (!category) {
    throw new AppError('Category not found', 404);
  }
  return category;
};

/**
 * Create a new category
 */
const createCategory = async (data) => {
  // Name uniqueness is handled by Mongoose unique index (causes duplicate key error handled globally)
  // Slug auto-generation is handled by mongoose pre-validate hook on the Category model
  const category = await Category.create(data);
  return category;
};

/**
 * Update an existing category
 */
const updateCategory = async (id, data) => {
  const category = await Category.findById(id);
  if (!category) {
    throw new AppError('Category not found', 404);
  }

  // Update fields manually so that pre-validate hook for slug regeneration fires if name changes
  if (data.name) category.name = data.name;
  if (data.description !== undefined) category.description = data.description;
  if (data.sortOrder !== undefined) category.sortOrder = data.sortOrder;
  if (data.isActive !== undefined) category.isActive = data.isActive;
  
  // Note: if name changes, slug regenerated by pre('validate') in model
  await category.save();

  return category;
};

/**
 * Delete a category (only if no products are linked)
 */
const deleteCategory = async (id) => {
  const category = await Category.findById(id);
  if (!category) {
    throw new AppError('Category not found', 404);
  }

  // Check if any products exist for this category
  const productsCount = await Product.countDocuments({ category: id });
  if (productsCount > 0) {
    throw new AppError(`Cannot delete category because it is associated with ${productsCount} product(s).`, 400);
  }

  await category.deleteOne();
};

/**
 * Reorder categories (bulk update sortOrder)
 * @param {Array} orderedIds - Array of category IDs in the new order
 */
const reorderCategories = async (orderedIds) => {
  // Perform bulk write for efficiency
  const bulkOps = orderedIds.map((id, index) => ({
    updateOne: {
      filter: { _id: id },
      update: { sortOrder: index },
    },
  }));

  if (bulkOps.length > 0) {
    await Category.bulkWrite(bulkOps);
  }
};

module.exports = {
  getAllCategories,
  getCategoryById,
  getCategoryBySlug,
  createCategory,
  updateCategory,
  deleteCategory,
  reorderCategories,
};
